---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
    - app.kubernetes.io/name: schema-pusher
    - helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    - app.kubernetes.io/managed-by: {{ .Release.Service }}
    - app.kubernetes.io/instance: {{ .Release.Name }}
    {{- range $.Values.labels }}
        {{ . }}
    {{- end }}
data:
  kafka.bootstrap: {{ .Values.kafka.bootstrap }} \
  service.registry: {{ .Values.service.registry }}
  naming.strategy: {{ .Values.naming.strategy }}
  topics: {{ join "," .Values.topics }}
binaryData:
  encoded.archive: {{ .Values.encoded.archive }}
immutable: true
