---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
    {{- include "resource.labels" . | nindent 4 }}
data:
  kafka.bootstrap: {{ .Values.kafka.bootstrap }} \
  service.registry: {{ .Values.service.registry }}
  naming.strategy: {{ .Values.naming.strategy }}
  topics: {{ join "," .Values.topics }}
binaryData:
  encoded.archive: {{ .Values.encoded.archive }}
immutable: true
