---
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-pod
  labels:
    {{- include "resource.labels" . | nindent 4 }}
spec:
  volumes:
  - name: config
    configMap:
      name: {{ .Release.Name }}-configmap
  {{- if .Values.kafka.certificates }}
  {{- if .Values.kafka.certificates.server }}
  - name: kafka-server-certificate
    secret:
      secretName: {{ .Values.kafka.certificates.server.secret }}
  {{- end }}
  {{- if .Values.kafka.certificates.user }}
  - name: kafka-user-certificate
    secret:
      secretName: {{ .Values.kafka.certificates.user.secret }}
  {{- end }}
  {{- end }}
  restartPolicy: Never
  containers:
  - name: {{ .Release.Name }}-container
    image: quay.io/ecosystem-appeng/schema-pusher:{{ .Chart.AppVersion }}
    command: [ "/bin/bash", "-c", "--" ]
    args:
      - >
        topic_args=""
        && schema_args=""
        && for((t=0; ;++t)); do if test -f "/config/topic$t"; then topic_args+=" --topic $(cat /config/topic$t)"; else break; fi; done
        && for((s=0; ;++s)); do if test -f "/config/schema$s"; then schema_args+=" --schema $(cat /config/schema$s | base64 -w 0 -)"; else break; fi; done
        && /app/entrypoint.sh
        --bootstrap $(cat /config/kafka.bootstrap)
        --registry $(cat /config/service.registry)
        --strategy $(cat /config/naming.strategy)
        $topic_args
        $schema_args
      {{- if .Values.kafka.certificates }}
      {{- if .Values.kafka.certificates.server }}
        --truststore $(cat /config/kafka.certificates.server/ca.p12 | base64 -w 0 -)
        --truststorePassword $(cat /config/kafka.certificates.server/ca.password)
      {{- end }}
      {{- if .Values.kafka.certificates.user }}
        --keystore $(cat /config/kafka.certificates.user/user.p12 | base64 -w 0 -)
        --keystorePassword $(cat /config/kafka.certificates.user/user.password)
      {{- end }}
      {{- end }}
    volumeMounts:
    - name: config
      mountPath: /config
      readOnly: true
    {{- if .Values.kafka.certificates }}
    {{- if .Values.kafka.certificates.server }}
    - name: kafka-server-certificate
      mountPath: /config/kafka.certificates.server
      readOnly: true
    {{- end }}
    {{- if .Values.kafka.certificates.user }}
    - name: kafka-user-certificate
      mountPath: /config/kafka.certificates.user
      readOnly: true
    {{- end }}
    {{- end }}
