---
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-pod
  labels:
    {{- include "resource.labels" . | nindent 4 }}
spec:
  volumes:
  - name: config
    configMap:
      name: {{ .Release.Name }}-configmap
  {{- if .Values.kafka.certificate }}
  - name: kafka-certificate
    secret:
      secretName: {{ .Values.kafka.certificate.secret }}
  {{- end }}
  restartPolicy: Never
  containers:
  - name: {{ .Release.Name }}-container
    image: quay.io/ecosystem-appeng/schema-pusher:{{ .Chart.AppVersion }}
    command: [ "/bin/bash", "-c", "--" ]
    args:
      - >
        topic_args=""
        && IFS=',' read -ra topics <<< $(cat /config/topics)
        && for topic in "${topics[@]}"; do topic_args+=" --topic $topic"; done
        && /app/entrypoint.sh
        --bootstrap $(cat /config/kafka.bootstrap)
        --registry $(cat /config/service.registry)
        --strategy $(cat /config/naming.strategy)
        $topic_args
        --content $(cat /config/encoded.archive | base64 -w 0 -)
      {{- if .Values.kafka.certificate }}
        --certificate $(cat /config/kafka.certificate/ca.crt | base64 -w 0 -)
      {{- end }}
    volumeMounts:
    - name: config
      mountPath: /config
      readOnly: true
    {{- if .Values.kafka.certificate }}
    - name: kafka-certificate
      mountPath: /config/kafka.certificate
      readOnly: true
    {{- end }}
