{{ if .Values.keycloak.enabled }}
apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: {{ .Release.Name }}-keycloak
  namespace: {{ .Release.Namespace }}
  labels:
    {{- range $.Values.keycloak.labels }}
      {{ . }}
    {{- end }} 
spec:
  externalAccess:
    enabled: {{ .Values.keycloak.enableExternalAccess }}
  instances: {{ .Values.keycloak.instances}}
{{ end }}