apiVersion: registry.apicur.io/v1
kind: ApicurioRegistry
metadata:
  name: {{ .Values.name }}-{{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- range $.Values.labels }}
      {{ . }}
    {{- end }} 
spec:
  configuration:
    kafkasql:
      bootstrapServers: {{ .Values.bootstrapServers }}
      security:
        tls:
          keystoreSecretName: {{ .Values.userName }}-{{ .Release.Name }}
          truststoreSecretName: {{ .Values.clusterName }}-cluster-ca-cert
{{ if .Values.keycloak.enabled }}

    security:
      keycloak:
        url: "https://keycloak-{{ .Release.Namespace }}.{{ .Values.domain }}/auth"
        apiClientId: {{ .Values.keycloak.realm.uiClientID | quote }}
        uiClientId: {{ .Values.keycloak.realm.apiClientID | quote }}
        realm: "{{ .Release.Name }}-keycloak-realm"
{{ end }}
    logLevel: {{.Values.logLevel }}
    persistence: {{ .Values.persistence }}
  deployment:
    host: >-
      rh-service-registry-{{ .Release.Name }}-{{ .Release.Namespace }}