
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.userName }}-{{ .Release.Name }}
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
spec:
  authentication:
    type: tls
  authorization:
    acls:
      - host: '*'
        operation: All
        resource:
          name: '*'
          patternType: literal
          type: topic
      - host: '*'
        operation: All
        resource:
          name: '*'
          patternType: literal
          type: group
    type: simple
