global:
  install-operators-auto: false
  useRHSSOoperator: true
  installOG: false
  rhsr-subscription:
    install: false
    channel: 2.x
    installPlanApproval: Manual
    name: service-registry-operator
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: service-registry-operator.v2.0.2
  rhsso-subscription:
    channel: stable
    installPlanApproval: Manual
    name: rhsso-operator
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: rhsso-operator.7.5.1-opr-006

name: rh-service-registry
bootstrapServers: https://sut-kafka-external-bootstrap-fo-kafka-perf.fo-sut.pintc010042040201050a001.sut.azr.fusionoperate.io:443
namespace: fo-kafka-perf
userName: schema-registry-user
clusterName: sut-kafka
domain: fo-sut.pintc010042040201050a001.sut.azr.fusionoperate.io
logLevel: INFO
persistence: kafkasql
labels:
  - 'app: rhsr'
  - 'dep: rhsr-deployment' 

keycloak:
  enabled: true
  enableExternalAccess: true
  instances: 1
  realm:
    uiClientID: registry-ui-client
    apiClientID: registry-api-client
    adminUser:
      enabled: true
      name: finastra-admin
      password: 'a1s2d3f4'
    developerUser:
      enabled: true
      name: registry-developer
      password: 'a1s2d3f4'
    readerUser:
      enabled: true
      name: registry-user
      password: 'a1s2d3f4'
  labels:
  - 'app: keycloak'
  - 'dep: keycloak-deployment' 
  

auth:
  #set to false in order to disable the authentication proxy side car
  enabled: false
  #select the target address where to be redirected after authentication must contain protocol name (http/https) in case its not a domain name it ust include port number
  upstream: 'http://rh-service-registry-rh-service-registry-service:8080/'
  #set as true if you need to use email domain authentication
  useEmailDomain: false
  #select the mail domain to be allowed for authentication
  emailDomain: redhat.com
  #set true if you need to use role based authentication
  useSar: true
  #select the resource where access is needed for a user to it in order to be able to bypass the proxy
  #  "namespace":"app-dev","resource":"services","name":"proxy","verb":"get"}
  resource:
    namespace: "kafka-essence-demo"
    kind: "services"
    name: rh-service-registry-rh-service-registry-service
    verb: get
  #select cookie secret name must be 16 bytes or 24 or 32
  cookieSecretName: RHSERG1234567890123456
  #cookie saving refresh rate in seconds
  cookieRefreshSec: 0
  #number of replicas for the deployment
  replicas: 1
  #list of labels to add to all resources e.g:
  # labels:
  #   - 'someLabelName: someLabelValue'
  #   - 'someOtherLabelName: someOtherLabelValue'
  labels:
  - 'app: auth-proxy'
  - 'dep: rhsr-auth-proxy' 
