{{ if .Values.global.installOG }}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .Release.Namespace }}-og
  namespace: {{ .Release.Namespace }}
  annotations:
      "helm.sh/hook": "pre-install"
      "helm.sh/hook-weight": "-4"
spec:
  targetNamespaces:
  - {{ .Release.Namespace }}
{{ end }}