apiVersion: v1
kind: Secret
metadata:
  name: kafka-properties-{{ .Release.Name }}
  namespace: {{ .Release.namespace }}
stringData:
  kafka.properties: 
{{- range $key, $val := (lookup "v1" "Secret" "{{ .Release.Namespace }}" "{{ .Values.kafka.truststoreSecret }}").data }}
{{ if ((eq $key "ca.password")) }}
    ssl.truststore.password={{ $val | b64dec | quote | nindent 4 }}
{{ end }}
{{- end }}

{{- range $key, $val := (lookup "v1" "Secret" "{{ .Release.Namespace }}" "{{ .Values.kafka.keystoreSecret }}").data }}
{{ if ((eq $key "user.password")) }}
    ssl.keystore.password={{ $val | b64dec | quote | nindent 4 }}
    ssl.key.password={{ $val | b64dec | quote | nindent 4 }}
{{ end }}
{{- end }}
{{ .Values.kafkaProperties | nindent 4 }} 
