auth:
  #set to false in order to disable the authentication proxy side car
  enabled: true
  #select the target address where to be redirected after authentication must contain protocol name (http/https) in case its not a domain name it ust include port number
  upstream: 'http://upstream-kafka-ui:80'
  #set as true if you need to use email domain authentication
  useEmailDomain: true
  #select the mail domain to be allowed for authentication
  emailDomain: redhat.com
  #set true if you need to use role based authentication
  useSar: true
  #select the resource where access is needed for a user to it in order to be able to bypass the proxy
  #  "namespace":"app-dev","resource":"services","name":"proxy","verb":"get"}
  resource:
    namespace: "nemer-amq"
    kind: "services"
    name: city-bank-kafka-ui
    verb: get
  #select cookie secret name must be 16 bytes or 24 or 32
  cookieSecretName: SECRET1234567890123456
  #cookie saving refresh rate in seconds
  cookieRefreshSec: 20
  #number of replicas for the deployment
  replicas: 1
  #list of labels to add to all resources e.g:
    # labels:
    #   - 'someLabelName: someLabelValue'
    #   - 'someOtherLabelName: someOtherLabelValue'
  labels:
    - 'app: proxy'