---
name: Deploy New Chart

on:
  workflow_dispatch:
    inputs:
      new_semver:
        description: "New Semantic Version"
        required: true
      chart_dir:
        description: "Chart Directory"
        required: true

env:
  HELM_REPO_URL: "https://RHEcosystemAppEng.github.io/fsi-common-helm"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Package and deploy a new chart version
    steps:
      - name: Source checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0

      - name: Get chart name
        id: chart_name
        run: echo "::set-output name=name::$(cat ${{ github.event.inputs.chart_dir }}/Chart.yaml | grep 'name:' | cut -c 7-)"

      - name: Update chart version
        run: |
          sed -i 's/version: .*/version: ${{ github.event.inputs.new_semver }}/g' ${{ github.event.inputs.chart_dir }}/Chart.yaml

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Setup Helm
        uses: azure/setup-helm@v1.1

      - name: Lint chart
        run: helm lint ${{ github.event.inputs.chart_dir }}

      - name: Package chart
        run: helm package ${{ github.event.inputs.chart_dir }}

      - name: Push new chart file
        run: |
          git add ${{ github.event.inputs.chart_dir }}/Chart.yaml
          git commit -m "build: bumped ${{ steps.chart_name.outputs.name }} to ${{ github.event.inputs.new_semver }} [skip ci]"
          git push

      - name: GH-Pages checkout
        run: git checkout gh-pages

      - name: Update repository index
        run: helm repo index --url ${{ env.HELM_REPO_URL }} .

      - name: Deploy new chart
        run: |
          git add ${{ steps.chart_name.outputs.name }}-${{ github.event.inputs.new_semver }}.tgz
          git add index.yaml
          git commit -m "chore: deployed ${{ steps.chart_name.outputs.name }} ${{ github.event.inputs.new_semver }}"
          git push
